import { defineStore } from 'pinia'

const dictionaries = {
  es: {
    nav: {
      home: 'Inicio',
      login: 'Login',
      service: 'Solicitar servicio',
      logout: 'Cerrar sesión',
    },
    language: {
      english: 'English',
      spanish: 'Español',
    },
    common: {
      access: 'Acceso',
      publicRequest: 'Solicitud pública',
      loading: 'Cargando...',
      cancel: 'Cancelar',
      confirmLogout: 'Sí, cerrar sesión',
      save: 'Guardar',
      edit: 'Editar',
      delete: 'Eliminar',
      creating: 'Creando...',
      updating: 'Actualizando...',
      created: 'Creado',
      updated: 'Actualizado',
      confirmed: 'Entendido',
    },
    logout: {
      title: 'Cerrar sesión',
      text: '¿Quieres salir de tu cuenta?',
    },
    login: {
      title: 'Iniciar sesión',
      subtitle: 'Ingresa con tu cuenta para ver servicios, cotizaciones y mensajes.',
      email: 'Correo electrónico',
      password: 'Contraseña',
      button: 'Entrar',
      loading: 'Entrando...',
      error: 'No se pudo iniciar sesión',
      alt: 'TECH SOLUTIONS',
    },
    services: {
      title: 'Solicita un servicio técnico',
      subtitle: 'No necesitas cuenta. Deja tus datos y el equipo técnico recibirá tu solicitud.',
      name: 'Nombre completo',
      phone: 'Teléfono',
      email: 'Correo electrónico',
      address: 'Dirección del servicio',
      postalCode: 'Código postal',
      type: 'Tipo de servicio',
      date: 'Fecha y hora',
      description: 'Describe la falla o lo que necesitas',
      submit: 'Enviar solicitud',
      submitting: 'Enviando...',
      success: 'Solicitud enviada. Tu código es',
      saveError: 'No se pudo enviar la solicitud',
      alt: 'TECH SOLUTIONS',
    },
    register: {
      title: 'Crear cuenta',
      subtitle: 'Registra clientes, técnicos o cuentas administrativas con el flujo inicial.',
      badge: 'Registro',
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      roleCustomer: 'Cuenta normal',
      roleAdmin: 'Cuenta admin',
      password: 'Contraseña',
      button: 'Registrarme',
      loading: 'Creando...',
      successAdmin: 'Cuenta admin creada. Ahora puedes iniciar sesión.',
      successCustomer: 'Cuenta creada. Ahora puedes iniciar sesión.',
      error: 'No se pudo registrar la cuenta',
    },
    dashboard: {
      servicesLoaded: 'Servicios cargados',
      pending: 'Pendientes',
      inProgress: 'En gestión',
      postalCode: 'Código postal',
      statuses: {
        pending: 'Pendiente',
        assigned: 'Asignado',
        inProgress: 'En progreso',
        completed: 'Completado',
        cancelled: 'Cancelado',
      },
      priorities: {
        low: 'Baja',
        normal: 'Normal',
        medium: 'Media',
        high: 'Alta',
      },
      title: 'Servicios recibidos',
      subtitle: 'Aquí puedes ver y actualizar el estado de las solicitudes que llegaron al sistema.',
      refresh: 'Refrescar',
      refreshing: 'Actualizando...',
      service: 'Servicio',
      client: 'Cliente',
      postalCode: 'Código postal',
      code: 'Código',
      status: 'Estado',
      priority: 'Prioridad',
      date: 'Fecha',
      actions: 'Acciones',
      noAddress: 'Sin dirección',
      noPostalCode: 'Sin código postal',
      noName: 'Sin nombre',
      noEmail: 'Sin correo',
      saving: 'Guardando...',
      save: 'Guardar',
      empty: 'No hay servicios para mostrar todavía.',
      noDate: 'Sin fecha',
      errorLoad: 'No se pudieron cargar los servicios',
      noManage: 'No tienes permisos para gestionar servicios',
      errorUpdate: 'No se pudo actualizar el servicio',
      noDelete: 'No tienes permisos para eliminar servicios',
      deleteTitle: 'Eliminar servicio',
      deleteConfirm: 'Sí, eliminar',
      deleteCancel: 'Cancelar',
      deleteOk: 'Entendido',
      deleteText: '¿Eliminar el servicio',
      deleteSuccess: 'Servicio eliminado.',
      deleteDoneTitle: 'Eliminado',
      deleteDoneText: 'El servicio fue eliminado correctamente.',
      deleteErrorTitle: 'No se pudo eliminar',
      deleteError: 'No se pudo eliminar el servicio',
      deletePrompt: '¿Eliminar el servicio',
      updatedMessage: 'Servicio actualizado.',
    },
    adminDashboard: {
      assigned: 'Servicios asignados',
      pendingQuotes: 'Cotizaciones pendientes',
      invoices: 'Facturas por cobrar',
      commercialFlow: 'Flujo comercial',
      commercialText: 'Alta de servicio, cotización, aprobación, factura y pago.',
      operation: 'Operación',
      operationText: 'Técnicos, agenda, monitoreo y escalado de incidencias.',
      userManagement: 'Gestión de usuarios',
      userManagementText: 'Crea, edita y elimina usuarios desde el panel administrativo.',
      openUsers: 'Abrir usuarios',
    },
    adminUsers: {
      title: 'Gestión de usuarios',
      back: 'Volver',
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      password: 'Contraseña inicial',
      roleCustomer: 'Cliente',
      roleTechnician: 'Técnico',
      roleAdmin: 'Administrador',
      active: 'Usuario activo',
      creating: 'Creando...',
      updating: 'Actualizando...',
      createUser: 'Crear usuario',
      updateUser: 'Actualizar usuario',
      cancelEdit: 'Cancelar edición',
      loading: 'Cargando usuarios...',
      headerName: 'Nombre',
      headerEmail: 'Email',
      headerRole: 'Rol',
      headerState: 'Estado',
      headerActions: 'Acciones',
      activeState: 'Activo',
      inactiveState: 'Inactivo',
      edit: 'Editar',
      delete: 'Eliminar',
      errorLoad: 'Error cargando usuarios',
      deleteTitle: 'Eliminar usuario',
      deleteConfirm: 'Sí, eliminar',
      deleteCancel: 'Cancelar',
      deleteOk: 'Aceptar',
      deletedTitle: 'Eliminado',
      deleteErrorTitle: 'No se pudo eliminar',
      deleteError: 'Error eliminando el usuario',
      deleted: 'Usuario eliminado correctamente.',
      deletedText: 'El usuario fue eliminado correctamente.',
      updated: 'Usuario actualizado correctamente.',
      created: 'Usuario creado correctamente.',
      errorUpdate: 'Error actualizando el usuario',
      errorCreate: 'Error creando el usuario',
      deletePrompt: '¿Eliminar al usuario',
    },
    adminServices: {
      title: 'Gestión de servicios',
      loading: 'Cargando solicitudes...',
      headerService: 'Servicio',
      headerContact: 'Contacto',
      headerStatus: 'Estado',
      headerCode: 'Código',
      headerActions: 'Acciones',
      noName: 'Sin nombre',
      noEmail: 'Sin email',
      noPhone: 'Sin teléfono',
      viewEdit: 'Ver / Editar',
      statuses: {
        pending: 'Pendiente',
        assigned: 'Asignado',
        inProgress: 'En progreso',
        completed: 'Completado',
        cancelled: 'Cancelado',
      },
      errorLoad: 'Error cargando solicitudes',
      editTitle: 'Editar solicitud',
      editText: 'Solicitud',
      editOk: 'Entendido',
    },
    notifications: {
      loading: 'Cargando...',
      empty: 'Sin notificaciones',
    },
    landing: {
      heroTitleStart: 'Soluciones técnicas',
      heroTitleAccent: '24/7',
      heroTitleEnd: 'para hogares y negocios.',
      heroCopy: 'Instalación, mantenimiento preventivo, reparaciones y soporte técnico especializado en un solo lugar.',
      createAccount: 'Crear cuenta',
      accessSystem: 'Acceder al sistema',
      metrics: {
        support: 'Atención de emergencias',
        completed: 'Servicios completados',
        response: 'Tiempo promedio de respuesta',
      },
      reviewWidget: {
        title: 'Deja tu valoración',
        hint: 'Elige una puntuación y escribe tu reseña',
        prompt: 'Cuéntanos qué te pareció el servicio',
        namePlaceholder: 'Tu nombre (opcional)',
        textPlaceholder: 'Escribe aquí tu reseña...',
        send: 'Enviar reseña',
        sending: 'Enviando...',
        empty: 'Escribe una reseña para enviarla.',
        ratingRequired: 'Selecciona una puntuación antes de enviar.',
        success: 'Gracias por tu reseña, ya fue publicada.',
        error: 'No se pudo guardar tu reseña. Inténtalo de nuevo.',
      },
      requestTitle: 'SOLICITA UN SERVICIO',
      requestText: 'Envía tu solicitud de servicio sin salir de la portada y el equipo la verá y te ayudará con la gestión.',
      requestButton: 'Agendar servicio',
      requestSuccess: 'Solicitud enviada. Código de seguimiento:',
      requestError: 'No se pudo agendar el servicio',
      nextTitle: 'Recepción y seguimiento',
      nextText: 'Tu solicitud se registra, se asigna prioridad y aparece en el dashboard para gestión operativa.',
      steps: ['Guardas la solicitud', 'Se genera código de seguimiento', 'El equipo la ve en el dashboard'],
      quickLinks: 'Enlaces Rápidos',
      servicesListTitle: 'Servicios',
      contactTitle: 'Contacto',
      serviceItems: {
        hvac: 'HVAC',
        electricity: 'Electricidad',
        plumbing: 'Plomería',
        security: 'Seguridad',
        automation: 'Automatización',
        maintenance: 'Mantenimiento General',
        support: 'Atención 24 horas / 7 días',
      },
      aboutUs: 'Sobre Nosotros',
      howItWorks: 'Cómo Funciona',
      contactLink: 'Contacto',
      servicesSection: {
        badge: 'NUESTROS SERVICIOS',
        title: 'Soluciones completas para su propiedad',
        benefitsLabel: 'Beneficios del servicio',
        items: {
          hvac: {
            title: 'HVAC',
            description: 'Instalación, mantenimiento y reparación de sistemas de aire acondicionado.',
          },
          electrical: {
            title: 'Eléctrico',
            description: 'Instalaciones, reparaciones y mantenimiento eléctrico residencial y comercial.',
          },
          plumbing: {
            title: 'Plomería',
            description: 'Detección de fugas, reparación de tuberías, grifería y remodelaciones.',
          },
          security: {
            title: 'Sistemas de seguridad',
            description: 'Instalación de cámaras, alarmas y monitoreo remoto 24/7.',
          },
          smartHome: {
            title: 'Smart Home',
            description: 'Automatización de iluminación, cerraduras, termostatos y sensores.',
          },
          handyman: {
            title: 'Servicios handyman',
            description: 'Reparaciones generales, pintura, instalación y mantenimiento.',
          },
        },
        benefits: {
          certified: 'Técnicos certificados',
          attention24h: 'Atención 24 horas',
          transparentQuotes: 'Presupuestos transparentes',
          serviceWarranty: 'Garantía en servicios',
          bilingualSupport: 'Soporte bilingüe (Inglés y Español)',
        },
      },
      reviewsSection: {
        badge: 'RESEÑAS DE CLIENTES',
        title: 'Lo que dicen nuestros clientes',
        subtitle: 'Mostramos reseñas reales ordenadas por fecha, 10 por página.',
        loading: 'Cargando reseñas...',
        empty: 'Aún no hay reseñas publicadas.',
        loadError: 'No se pudieron cargar las reseñas.',
        anonymous: 'Cliente anónimo',
        prev: 'Anterior',
        next: 'Siguiente',
        page: 'Página',
      },
      footerText: 'Soluciones técnicas 24/7 para hogares y negocios. Calidad, confianza y rapidez en cada servicio.',
      copyright: '© 2024 24HR Tech Solutions. Todos los derechos reservados.',
      alt: '24HR Tech Solutions',
    },
  },
  en: {
    nav: {
      home: 'Home',
      login: 'Login',
      service: 'Request service',
      logout: 'Log out',
    },
    language: {
      english: 'English',
      spanish: 'Español',
    },
    common: {
      access: 'Access',
      publicRequest: 'Public request',
      loading: 'Loading...',
      cancel: 'Cancel',
      confirmLogout: 'Yes, log out',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      creating: 'Creating...',
      updating: 'Updating...',
      created: 'Created',
      updated: 'Updated',
      confirmed: 'Understood',
    },
    logout: {
      title: 'Log out',
      text: 'Do you want to sign out?',
    },
    login: {
      title: 'Sign in',
      subtitle: 'Log in to view services, quotes, and messages.',
      email: 'Email address',
      password: 'Password',
      button: 'Enter',
      loading: 'Entering...',
      error: 'Could not sign in',
      alt: 'TECH SOLUTIONS',
    },
    services: {
      title: 'Request a technical service',
      subtitle: 'No account needed. Leave your details and the technical team will receive your request.',
      name: 'Full name',
      phone: 'Phone',
      email: 'Email address',
      address: 'Service address',
      postalCode: 'Postal code',
      type: 'Service type',
      date: 'Date and time',
      description: 'Describe the issue or what you need',
      submit: 'Send request',
      submitting: 'Sending...',
      success: 'Request sent. Your code is',
      saveError: 'Could not send the request',
      alt: 'TECH SOLUTIONS',
    },
    register: {
      title: 'Create account',
      subtitle: 'Register customers, technicians, or administrative accounts with the initial flow.',
      badge: 'Register',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email address',
      phone: 'Phone',
      roleCustomer: 'Customer account',
      roleAdmin: 'Admin account',
      password: 'Password',
      button: 'Sign up',
      loading: 'Creating...',
      successAdmin: 'Admin account created. You can sign in now.',
      successCustomer: 'Account created. You can sign in now.',
      error: 'Could not register the account',
    },
    dashboard: {
      servicesLoaded: 'Services loaded',
      pending: 'Pending',
      inProgress: 'In progress',
      postalCode: 'Postal code',
      statuses: {
        pending: 'Pending',
        assigned: 'Assigned',
        inProgress: 'In progress',
        completed: 'Completed',
        cancelled: 'Cancelled',
      },
      priorities: {
        low: 'Low',
        normal: 'Normal',
        medium: 'Medium',
        high: 'High',
      },
      title: 'Services received',
      subtitle: 'Here you can view and update the status of the requests that reached the system.',
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      service: 'Service',
      client: 'Client',
      postalCode: 'Postal code',
      code: 'Code',
      status: 'Status',
      priority: 'Priority',
      date: 'Date',
      actions: 'Actions',
      noAddress: 'No address',
      noPostalCode: 'No postal code',
      noName: 'No name',
      noEmail: 'No email',
      saving: 'Saving...',
      save: 'Save',
      empty: 'No services to show yet.',
      noDate: 'No date',
      errorLoad: 'Could not load services',
      noManage: 'You do not have permission to manage services',
      errorUpdate: 'Could not update the service',
      noDelete: 'You do not have permission to delete services',
      deleteTitle: 'Delete service',
      deleteConfirm: 'Yes, delete',
      deleteCancel: 'Cancel',
      deleteOk: 'OK',
      deletedTitle: 'Deleted',
      deleteErrorTitle: 'Could not delete',
      deleteError: 'Could not delete the service',
      deletePrompt: 'Delete service',
      updatedMessage: 'Service updated.',
      deleteSuccess: 'Service deleted.',
      deleteDoneTitle: 'Deleted',
      deleteDoneText: 'The service was deleted successfully.',
    },
    adminDashboard: {
      assigned: 'Assigned services',
      pendingQuotes: 'Pending quotes',
      invoices: 'Invoices due',
      commercialFlow: 'Commercial flow',
      commercialText: 'Service intake, quote, approval, invoice, and payment.',
      operation: 'Operations',
      operationText: 'Technicians, schedule, monitoring, and incident escalation.',
      userManagement: 'User management',
      userManagementText: 'Create, edit, and delete users from the admin panel.',
      openUsers: 'Open users',
    },
    adminUsers: {
      title: 'User management',
      back: 'Back',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email address',
      phone: 'Phone',
      password: 'Initial password',
      roleCustomer: 'Customer',
      roleTechnician: 'Technician',
      roleAdmin: 'Administrator',
      active: 'Active user',
      creating: 'Creating...',
      updating: 'Updating...',
      createUser: 'Create user',
      updateUser: 'Update user',
      cancelEdit: 'Cancel edit',
      loading: 'Loading users...',
      headerName: 'Name',
      headerEmail: 'Email',
      headerRole: 'Role',
      headerState: 'State',
      headerActions: 'Actions',
      activeState: 'Active',
      inactiveState: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      errorLoad: 'Error loading users',
      deleteTitle: 'Delete user',
      deleteConfirm: 'Yes, delete',
      deleteCancel: 'Cancel',
      deleteOk: 'OK',
      deletedTitle: 'Deleted',
      deleteErrorTitle: 'Could not delete',
      deleteError: 'Error deleting the user',
      deleted: 'User deleted successfully.',
      deletedText: 'The user was deleted successfully.',
      updated: 'User updated successfully.',
      created: 'User created successfully.',
      errorUpdate: 'Error updating the user',
      errorCreate: 'Error creating the user',
      deletePrompt: 'Delete user',
    },
    adminServices: {
      title: 'Service management',
      loading: 'Loading requests...',
      headerService: 'Service',
      headerContact: 'Contact',
      headerStatus: 'Status',
      headerCode: 'Code',
      headerActions: 'Actions',
      noName: 'No name',
      noEmail: 'No email',
      noPhone: 'No phone',
      viewEdit: 'View / Edit',
      statuses: {
        pending: 'Pending',
        assigned: 'Assigned',
        inProgress: 'In progress',
        completed: 'Completed',
        cancelled: 'Cancelled',
      },
      errorLoad: 'Error loading requests',
      editTitle: 'Edit request',
      editText: 'Request',
      editOk: 'Understood',
    },
    notifications: {
      loading: 'Loading...',
      empty: 'No notifications',
    },
    landing: {
      heroTitleStart: 'Technical solutions',
      heroTitleAccent: '24/7',
      heroTitleEnd: 'for homes and businesses.',
      heroCopy: 'Installation, preventive maintenance, repairs, and specialized technical support in one place.',
      createAccount: 'Create account',
      accessSystem: 'Access system',
      metrics: {
        support: 'Emergency support',
        completed: 'Services completed',
        response: 'Average response time',
      },
      reviewWidget: {
        title: 'Leave your rating',
        hint: 'Pick a score and write your review',
        prompt: 'Tell us what you thought about the service',
        namePlaceholder: 'Your name (optional)',
        textPlaceholder: 'Write your review here...',
        send: 'Submit review',
        sending: 'Submitting...',
        empty: 'Write a review before sending it.',
        ratingRequired: 'Select a rating before submitting.',
        success: 'Thanks for your review, it is now published.',
        error: 'Your review could not be saved. Please try again.',
      },
      requestTitle: 'REQUEST A SERVICE',
      requestText: 'Submit your service request without leaving the homepage and the team will review it and help manage it.',
      requestButton: 'Schedule service',
      requestSuccess: 'Request sent. Tracking code:',
      requestError: 'Could not schedule the service',
      nextTitle: 'Intake and follow-up',
      nextText: 'Your request is recorded, prioritized, and appears in the dashboard for operational management.',
      steps: ['You save the request', 'A tracking code is generated', 'The team sees it in the dashboard'],
      quickLinks: 'Quick Links',
      servicesListTitle: 'Services',
      contactTitle: 'Contact',
      serviceItems: {
        hvac: 'HVAC',
        electricity: 'Electricity',
        plumbing: 'Plumbing',
        security: 'Security',
        automation: 'Automation',
        maintenance: 'General Maintenance',
        support: '24 hours / 7 days support',
      },
      aboutUs: 'About Us',
      howItWorks: 'How It Works',
      contactLink: 'Contact',
      servicesSection: {
        badge: 'OUR SERVICES',
        title: 'Complete solutions for your property',
        benefitsLabel: 'Service benefits',
        items: {
          hvac: {
            title: 'HVAC',
            description: 'Installation, maintenance, and repair of air conditioning systems.',
          },
          electrical: {
            title: 'Electrical',
            description: 'Residential and commercial electrical installations, repairs, and maintenance.',
          },
          plumbing: {
            title: 'Plumbing',
            description: 'Leak detection, pipe and fixture repair, and remodeling support.',
          },
          security: {
            title: 'Security systems',
            description: 'Camera and alarm installation with 24/7 remote monitoring.',
          },
          smartHome: {
            title: 'Smart Home',
            description: 'Lighting, lock, thermostat, and sensor automation.',
          },
          handyman: {
            title: 'Handyman services',
            description: 'General repairs, painting, installation, and maintenance.',
          },
        },
        benefits: {
          certified: 'Certified technicians',
          attention24h: '24-hour support',
          transparentQuotes: 'Transparent quotes',
          serviceWarranty: 'Service warranty',
          bilingualSupport: 'Bilingual support (English and Spanish)',
        },
      },
      reviewsSection: {
        badge: 'CUSTOMER REVIEWS',
        title: 'What our customers say',
        subtitle: 'We show real reviews sorted by date, 10 per page.',
        loading: 'Loading reviews...',
        empty: 'No reviews have been published yet.',
        loadError: 'Reviews could not be loaded.',
        anonymous: 'Anonymous customer',
        prev: 'Previous',
        next: 'Next',
        page: 'Page',
      },
      footerText: '24/7 technical solutions for homes and businesses. Quality, trust, and speed in every service.',
      copyright: '© 2024 24HR Tech Solutions. All rights reserved.',
      alt: '24HR Tech Solutions',
    },
  },
}

const defaultLocale = typeof localStorage !== 'undefined' && localStorage.getItem('locale') === 'en' ? 'en' : 'es'

const applyLocale = (locale) => {
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale
  }
}

applyLocale(defaultLocale)

const resolvePath = (source, key) => key.split('.').reduce((value, part) => (value && value[part] !== undefined ? value[part] : undefined), source)

export const useLanguageStore = defineStore('language', {
  state: () => ({
    locale: defaultLocale,
  }),
  actions: {
    setLocale(locale) {
      this.locale = locale === 'en' ? 'en' : 'es'
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('locale', this.locale)
      }
      applyLocale(this.locale)
    },
    t(key) {
      const localeDictionary = dictionaries[this.locale] || dictionaries.es
      return resolvePath(localeDictionary, key) ?? key
    },
  },
})